### ISSUE TITLE
Limit method error

### ISSUE THREAD

**Issue by ozanmuyes** [adam-cowley/neode-querybuilder#2]
The build query;

```js
const { cypher, params } = (new Builder())
  .match('p', 'Person')
  .return('p')
  .orderBy('p.name', Order.ASC)
  .skip(13)
  .limit(42)
  .build();
```

yields this as the `cypher`;

```cypher
MATCH (p:Person)
RETURN p
ORDER BY p.name ASC
SKIP 13
LIMIT 13
```

which is wrong (obviously). Also it doesn't matter if limit called before or after skip. It builds correct query **without** limit.

**Comment by adam-cowley** [comment]
Weird... I remember seeing this but thought I'd fixed it.  I've just updated builder.test.ts to double check and it seems fine. 

```ts
const { cypher } = builder
    .match('this', 'Node')
    .return('this')
    .skip(10)
    .limit(20)
    .build();

expect(cypher).toBe([
    `MATCH (this:Node)`,
    `RETURN this`,
    `SKIP 10`,
    `LIMIT 20`,
].join('\n'))
```

Gives:
```cypher
MATCH (this:Node)
RETURN this
SKIP 10
LIMIT 20
```

Maybe there was a mixup with the build/publish to npm.  I've bumped the version number and republished, hopefully that will fix the problem.  Let me know if it doesn't.

**Comment by ozanmuyes** [comment]
Yes, I can confirm that statement file in the src directory correct, but the file in the dist directory wrong. 
<img width="594" alt="Screen Shot 2020-04-10 at 12 02 46" src="https://user-images.githubusercontent.com/1537985/78978806-3adf3580-7b23-11ea-9cdb-af88124cbe20.png">

**Comment by ozanmuyes** [comment]
Also now the dist directory lacks of index.js, don't know why

**Comment by adam-cowley** [comment]
Strange, it looks like the build script wasn't configured correctly.  I'm not sure if updating typescript did something?  It should be fine now with v0.1.2

**Comment by ozanmuyes** [comment]
It is OK with the latest version (v0.1.2).
